CREATE TABLE Users(
id INT PRIMARY KEY IDENTITY,
Email VARCHAR(50) NOT NULL UNIQUE,
Pwd VARCHAR(100) NOT NULL,
Lastname VARCHAR(50),
Firstname VARCHAR(50),
Suspended BIT NOT NULL DEFAULT 0,
LoginFailCount INT NOT NULL DEFAULT 0
)